listen = "0.0.0.0:5080"
prefix="" 

WebDavPrefix="webdav"
ToolsPrefix="tools"

stlcrt = ""
stlkey = ""

[[users]]
  uid = "gdav"
  pwd = "123456"
  root = "../../"
  hides = [ 
    "oneproject/.git/",
    "down/",
    "cc/a.txt",
  ]

[[users]]
  uid = "test"
  pwd = "123456"
  root = "/root/test/"
